### ISSUE TITLE
AVs that detect and why

### ISSUE THREAD

**Issue by iamalsaher** [jbreed/apkinjector#2]
I am opening this to
1. Keep track of which AV is detecting the payload
2. Speculations on why it is detecting
3. Suggestions for evasions
4. What all we have tried for evasion and it's results
5. Some out of the box thinking

**Comment by iamalsaher** [comment]
Right now we have 

Avast
Extra permissions or detecting malicious payload
Try reducing permissions 

I found this as a potential reason as to why the app is being detected

https://forum.avast.com/index.php?topic=179031.0

It's reputation based and I guess nothing can be done about it, or if you can improve the reputation of a malware, you are welcome here

**Comment by jbreed** [comment]
Closing this here as there will be no future changes to APKInjector. Can re-open an issue tracking AV flags in APKWash.
